### ISSUE TITLE
Some RUN commands are not recognized

### ISSUE THREAD

**Issue by JamieMagee** [tern-tools/tern#918] opened 2021-03-17 21:42 UTC
**Describe the bug**
Scanning a docker image built using [buildkit](https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds), commands are not recognized

**To Reproduce**
1. Using the following Dockerfile
	```docker
	FROM node:slim
	RUN npm install -g serve
	```
2. `DOCKER_BUILDKIT=1 docker build . -t serve:latest`
3. `tern --driver fuse report --docker-image serve:latest`

**Error in terminal**

<details>
<summary>Details</summary>

```sh
Layer 6:
                warning: 
Unrecognized Commands:RUN npm install -g serve # buildkit

        File licenses found in Layer:  None
        Packages found in Layer:  None
        Licenses found in Layer:  None
```

</details>

**Expected behavior**

<details>
<summary>Details</summary>

```sh
 Layer 6:
                info: Retrieved by invoking listing in command_lib/base.yml
names:
        in container:
        npm list -g | sed 's/\(^[^a-z]*\)\([_.a-z0-9-]*\)\(@.*\)/\2/g' | grep -v '/usr*' | uniq

proj_urls:
        in container:
        pkgs=`npm list -g | sed 's/\(^[^a-z]*\)\([_.a-z0-9-]*\)\(@.*\)/\2/g' | grep -v '/usr*' | uniq`
        for p in $pkgs; do npm view $p repository.url; done

versions:
        in container:
        pkgs=`npm list -g | sed 's/\(^[^a-z]*\)\([_.a-z0-9-]*\)\(@.*\)/\2/g' | grep -v '/usr*' | uniq`
        for p in $pkgs; do npm show $p version; done

licenses:
        in container:
        pkgs=`npm list -g | sed 's/\(^[^a-z]*\)\([_.a-z0-9-]*\)\(@.*\)/\2/g' | grep -v '/usr*' | uniq`
        for p in $pkgs; do lic=`npm show $p license`; if [ -z "$lic" ]; then echo 'Unknown'; else echo $lic; fi; done



                error: npm notice 
npm notice New patch version of npm available! 7.6.0 -> 7.6.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.6.3>
npm notice Run `npm install -g npm@7.6.3` to update!
npm notice 

                warning: No listing method for 'copyrights'. Additional analysis may be required.
No listing method for 'srcs'. Additional analysis may be required.
No listing method for 'files'. Additional analysis may be required.

        File licenses found in Layer:  None
        Packages found in Layer:  None
        Licenses found in Layer:  None
------------------------------------------------
```

</details>

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version'
- Operating System (Linux Distro and version or Mac or Windows)
- Vagrant file
- Container OS
- Python version (3.6 or higher)
- Cloud environment (AWS, Azure, GCP)

**Please attach files if they exist**

**Comment by nishakm** [comment] 2021-03-17 22:49
:D I've been working on a backup method when the commands are not recognized. I'll reference this bug in the commit message.

**Comment by nishakm** [comment] 2021-04-07 14:58
The fix for this is dependent on #840 being merged

**Comment by nishakm** [comment] 2021-04-27 22:05
@JamieMagee are you referring to the `npm` command not being recognized? It's not recognized whether you use buildkit or not.

**Comment by rnjudge** [comment] 2021-04-27 22:41
@JamieMagee @nishakm The issue is with the `-g` option that npm install uses. When I use the following Dockerfile, Tern reports `npm` packages correctly:

```
FROM node:slim

WORKDIR /app
RUN npm install serve
```

<details>

```
=======================================================================================

	Layer 6:
		info: Layer created by commands: /bin/sh -c npm install serve
		info: Retrieved package metadata using npm default method. 

	File licenses found in Layer:  None
	Packages found in Layer: 
	+------------------------------------+---------+----------------+
	| Package                            | Version | License        |
	+------------------------------------+---------+----------------+
	| npm                                | 7.10.0  | Artistic-2.0   |
	| @npmcli/arborist                   | 2.3.0   | ISC            |
	| @npmcli/installed-package-contents | 1.0.7   | ISC            |
	| npm-bundled                        | 1.1.1   | ISC            |
	| npm-normalize-package-bin          | 1.0.1   | ISC            |
	| @npmcli/map-workspaces             | 1.0.3   | ISC            |
	| @npmcli/name-from-folder           | 1.0.1   | ISC            |
	| glob                               | 7.1.6   | ISC            |
	| minimatch                          | 3.0.4   | ISC            |
	| read-package-json-fast             | 2.0.2   | ISC            |
	| @npmcli/metavuln-calculator        | 1.1.1   | ISC            |
	| cacache                            | 15.0.6  | ISC            |
	| pacote                             | 11.3.1  | ISC            |
	| semver                             | 7.3.5   | ISC            |
	| @npmcli/move-file                  | 1.1.2   | MIT            |
	| mkdirp                             | 1.0.4   | MIT            |
	| rimraf                             | 3.0.2   | ISC            |
	| @npmcli/node-gyp                   | 1.0.2   | ISC            |
	| @npmcli/run-script                 | 1.8.4   | ISC            |
	| bin-links                          | 2.2.1   | ISC            |
	| cmd-shim                           | 4.1.0   | ISC            |
	| mkdirp-infer-owner                 | 2.0.0   | ISC            |
	| read-cmd-shim                      | 2.0.0   | ISC            |
	| write-file-atomic                  | 3.0.3   | ISC            |
	| common-ancestor-path               | 1.0.1   | ISC            |
	| json-parse-even-better-errors      | 2.3.1   | MIT            |
	| json-stringify-nice                | 1.1.3   | ISC            |
	| npm-install-checks                 | 4.0.0   | BSD-2-Clause   |
	| npm-package-arg                    | 8.1.2   | ISC            |
	| npm-pick-manifest                  | 6.1.1   | ISC            |
	| npm-registry-fetch                 | 9.0.0   | ISC            |
	| parse-conflict-json                | 1.1.1   | ISC            |
	| promise-all-reject-late            | 1.0.1   | ISC            |
	| promise-call-limit                 | 1.0.1   | ISC            |
	| readdir-scoped-modules             | 1.1.0   | ISC            |
	| tar                                | 6.1.0   | ISC            |
	| treeverse                          | 1.0.4   | ISC            |
	| walk-up-path                       | 1.0.0   | ISC            |
	| @npmcli/ci-detect                  | 1.3.0   | ISC            |
	| @npmcli/config                     | 2.1.0   | ISC            |
	| ini                                | 2.0.0   | ISC            |
	| nopt                               | 5.0.0   | ISC            |
	| @npmcli/promise-spawn              | 1.3.2   | ISC            |
	| infer-owner                        | 1.0.4   | ISC            |
	| node-gyp                           | 7.1.2   | MIT            |
	| abbrev                             | 1.1.1   | ISC            |
	| ansicolors                         | 0.3.2   | MIT            |
	| ansistyles                         | 0.1.3   | MIT            |
	| archy                              | 1.0.0   | MIT            |
	| byte-size                          | 7.0.1   | MIT            |
	| chownr                             | 2.0.0   | ISC            |
	| fs-minipass                        | 2.1.0   | ISC            |
	| minipass                           | 3.1.3   | ISC            |
	| lru-cache                          | 6.0.0   | ISC            |
	| yallist                            | 4.0.0   | ISC            |
	| minipass-collect                   | 1.0.2   | ISC            |
	| minipass-flush                     | 1.0.5   | ISC            |
	| minipass-pipeline                  | 1.2.4   | ISC            |
	| p-map                              | 4.0.0   | MIT            |
	| aggregate-error                    | 3.1.0   | MIT            |
	| clean-stack                        | 2.2.0   | MIT            |
	| indent-string                      | 4.0.0   | MIT            |
	| promise-inflight                   | 1.0.1   | ISC            |
	| ssri                               | 8.0.1   | ISC            |
	| unique-filename                    | 1.1.1   | ISC            |
	| unique-slug                        | 2.0.2   | ISC            |
	| imurmurhash                        | 0.1.4   | MIT            |
	| chalk                              | 4.1.0   | MIT            |
	| ansi-styles                        | 4.3.0   | MIT            |
	| color-convert                      | 2.0.1   | MIT            |
	| color-name                         | 1.1.4   | MIT            |
	| supports-color                     | 7.2.0   | MIT            |
	| has-flag                           | 4.0.0   | MIT            |
	| cli-columns                        | 3.1.2   | MIT            |
	| string-width                       | 2.1.1   | MIT            |
	| is-fullwidth-code-point            | 2.0.0   | MIT            |
	| strip-ansi                         | 4.0.0   | MIT            |
	| ansi-regex                         | 3.0.0   | MIT            |
	| cli-table3                         | 0.6.0   | MIT            |
	| colors                             | 1.4.0   | MIT            |
	| object-assign                      | 4.1.1   | MIT            |
	| emoji-regex                        | 8.0.0   | MIT            |
	| columnify                          | 1.5.4   | MIT            |
	| wcwidth                            | 1.0.1   | MIT            |
	| defaults                           | 1.0.3   | MIT            |
	| clone                              | 1.0.4   | MIT            |
	| fs.realpath                        | 1.0.0   | ISC            |
	| inflight                           | 1.0.6   | ISC            |
	| once                               | 1.4.0   | ISC            |
	| wrappy                             | 1.0.2   | ISC            |
	| inherits                           | 2.0.4   | ISC            |
	| brace-expansion                    | 1.1.11  | MIT            |
	| balanced-match                     | 1.0.2   | MIT            |
	| concat-map                         | 0.0.1   | MIT            |
	| path-is-absolute                   | 1.0.1   | MIT            |
	| graceful-fs                        | 4.2.6   | ISC            |
	| hosted-git-info                    | 4.0.2   | ISC            |
	| init-package-json                  | 2.0.2   | ISC            |
	| promzard                           | 0.3.0   | ISC            |
	| read                               | 1.0.7   | ISC            |
	| read-package-json                  | 3.0.1   | ISC            |
	| validate-npm-package-license       | 3.0.4   | Apache-2.0     |
	| spdx-correct                       | 3.1.1   | Apache-2.0     |
	| spdx-expression-parse              | 3.0.1   | MIT            |
	| spdx-license-ids                   | 3.0.7   | CC0-1.0        |
	| spdx-exceptions                    | 2.3.0   | CC-BY-3.0      |
	| validate-npm-package-name          | 3.0.0   | ISC            |
	| is-cidr                            | 4.0.2   | BSD-2-Clause   |
	| cidr-regex                         | 3.1.1   | BSD-2-Clause   |
	| ip-regex                           | 4.3.0   | MIT            |
	| leven                              | 3.1.0   | MIT            |
	| libnpmaccess                       | 4.0.1   | ISC            |
	| aproba                             | 2.0.0   | ISC            |
	| libnpmdiff                         | 2.0.4   | ISC            |
	| @npmcli/disparity-colors           | 1.0.1   | ISC            |
	| binary-extensions                  | 2.2.0   | MIT            |
	| diff                               | 5.0.0   | BSD-3-Clause   |
	| libnpmfund                         | 1.0.2   | ISC            |
	| libnpmhook                         | 6.0.1   | ISC            |
	| libnpmorg                          | 2.0.1   | ISC            |
	| libnpmpack                         | 2.0.1   | ISC            |
	| libnpmpublish                      | 4.0.0   | ISC            |
	| normalize-package-data             | 3.0.2   | BSD-2-Clause   |
	| resolve                            | 1.20.0  | MIT            |
	| is-core-module                     | 2.2.0   | MIT            |
	| has                                | 1.0.3   | MIT            |
	| function-bind                      | 1.1.1   | MIT            |
	| path-parse                         | 1.0.6   | MIT            |
	| libnpmsearch                       | 3.1.0   | ISC            |
	| libnpmteam                         | 2.0.2   | ISC            |
	| libnpmversion                      | 1.2.0   | ISC            |
	| @npmcli/git                        | 2.0.8   | ISC            |
	| promise-retry                      | 2.0.1   | MIT            |
	| which                              | 2.0.2   | ISC            |
	| stringify-package                  | 1.0.1   | ISC            |
	| make-fetch-happen                  | 8.0.14  | ISC            |
	| agentkeepalive                     | 4.1.4   | MIT            |
	| debug                              | 4.3.1   | MIT            |
	| ms                                 | 2.1.2   | MIT            |
	| depd                               | 1.1.2   | MIT            |
	| humanize-ms                        | 1.2.1   | MIT            |
	| http-cache-semantics               | 4.1.0   | BSD-2-Clause   |
	| http-proxy-agent                   | 4.0.1   | MIT            |
	| @tootallnate/once                  | 1.1.2   | MIT            |
	| agent-base                         | 6.0.2   | MIT            |
	| https-proxy-agent                  | 5.0.0   | MIT            |
	| is-lambda                          | 1.0.1   | MIT            |
	| minipass-fetch                     | 1.3.3   | MIT            |
	| encoding                           | 0.1.13  | MIT            |
	| iconv-lite                         | 0.6.2   | MIT            |
	| safer-buffer                       | 2.1.2   | MIT            |
	| minipass-sized                     | 1.0.3   | ISC            |
	| minizlib                           | 2.1.2   | MIT            |
	| err-code                           | 2.0.3   | MIT            |
	| retry                              | 0.12.0  | MIT            |
	| socks-proxy-agent                  | 5.0.0   | MIT            |
	| socks                              | 2.6.0   | MIT            |
	| ip                                 | 1.1.5   | MIT            |
	| smart-buffer                       | 4.1.0   | MIT            |
	| env-paths                          | 2.2.1   | MIT            |
	| npmlog                             | 4.1.2   | ISC            |
	| request                            | 2.88.2  | Apache-2.0     |
	| aws-sign2                          | 0.7.0   | Apache-2.0     |
	| aws4                               | 1.11.0  | MIT            |
	| caseless                           | 0.12.0  | Apache-2.0     |
	| combined-stream                    | 1.0.8   | MIT            |
	| delayed-stream                     | 1.0.0   | MIT            |
	| extend                             | 3.0.2   | MIT            |
	| forever-agent                      | 0.6.1   | Apache-2.0     |
	| form-data                          | 2.3.3   | MIT            |
	| asynckit                           | 0.4.0   | MIT            |
	| mime-types                         | 2.1.30  | MIT            |
	| har-validator                      | 5.1.5   | MIT            |
	| ajv                                | 6.12.6  | MIT            |
	| fast-deep-equal                    | 3.1.3   | MIT            |
	| fast-json-stable-stringify         | 2.1.0   | MIT            |
	| json-schema-traverse               | 0.4.1   | MIT            |
	| uri-js                             | 4.4.1   | BSD-2-Clause   |
	| punycode                           | 2.1.1   | MIT            |
	| har-schema                         | 2.0.0   | ISC            |
	| http-signature                     | 1.2.0   | MIT            |
	| assert-plus                        | 1.0.0   | MIT            |
	| jsprim                             | 1.4.1   | MIT            |
	| extsprintf                         | 1.3.0   | MIT            |
	| json-schema                        | 0.2.3   | Unknown        |
	| verror                             | 1.10.0  | MIT            |
	| core-util-is                       | 1.0.2   | MIT            |
	| sshpk                              | 1.16.1  | MIT            |
	| asn1                               | 0.2.4   | MIT            |
	| bcrypt-pbkdf                       | 1.0.2   | BSD-3-Clause   |
	| tweetnacl                          | 0.14.5  | Unlicense      |
	| dashdash                           | 1.14.1  | MIT            |
	| ecc-jsbn                           | 0.1.2   | MIT            |
	| jsbn                               | 0.1.1   | MIT            |
	| getpass                            | 0.1.7   | MIT            |
	| is-typedarray                      | 1.0.0   | MIT            |
	| isstream                           | 0.1.2   | MIT            |
	| json-stringify-safe                | 5.0.1   | ISC            |
	| mime-db                            | 1.47.0  | MIT            |
	| oauth-sign                         | 0.9.0   | Apache-2.0     |
	| performance-now                    | 2.1.0   | MIT            |
	| qs                                 | 6.5.2   | BSD-3-Clause   |
	| safe-buffer                        | 5.1.2   | MIT            |
	| tough-cookie                       | 2.5.0   | BSD-3-Clause   |
	| psl                                | 1.8.0   | MIT            |
	| tunnel-agent                       | 0.6.0   | Apache-2.0     |
	| uuid                               | 3.4.0   | MIT            |
	| npm-audit-report                   | 2.1.4   | ISC            |
	| npm-profile                        | 5.0.2   | ISC            |
	| minipass-json-stream               | 1.0.1   | MIT            |
	| jsonparse                          | 1.3.1   | MIT            |
	| npm-user-validate                  | 1.0.1   | BSD-2-Clause   |
	| are-we-there-yet                   | 1.1.5   | ISC            |
	| delegates                          | 1.0.0   | MIT            |
	| readable-stream                    | 2.3.7   | MIT            |
	| isarray                            | 1.0.0   | MIT            |
	| process-nextick-args               | 2.0.1   | MIT            |
	| string_decoder                     | 1.1.1   | MIT            |
	| util-deprecate                     | 1.0.2   | MIT            |
	| console-control-strings            | 1.1.0   | ISC            |
	| gauge                              | 2.7.4   | ISC            |
	| has-unicode                        | 2.0.1   | ISC            |
	| signal-exit                        | 3.0.3   | ISC            |
	| code-point-at                      | 1.1.0   | MIT            |
	| number-is-nan                      | 1.0.1   | MIT            |
	| wide-align                         | 1.1.3   | ISC            |
	| set-blocking                       | 2.0.0   | ISC            |
	| opener                             | 1.5.2   | (WTFPL OR MIT) |
	| npm-packlist                       | 2.1.5   | ISC            |
	| ignore-walk                        | 3.0.3   | ISC            |
	| just-diff-apply                    | 3.0.0   | MIT            |
	| just-diff                          | 3.1.1   | MIT            |
	| qrcode-terminal                    | 0.12.0  | Unknown        |
	| mute-stream                        | 0.0.8   | ISC            |
	| debuglog                           | 1.0.1   | MIT            |
	| dezalgo                            | 1.0.3   | ISC            |
	| asap                               | 2.0.6   | MIT            |
	| text-table                         | 0.2.0   | MIT            |
	| tiny-relative-date                 | 1.3.0   | MIT            |
	| builtins                           | 1.0.3   | MIT            |
	| isexe                              | 2.0.0   | ISC            |
	| typedarray-to-buffer               | 3.1.5   | MIT            |
	+------------------------------------+---------+----------------+
=======================================================================================

```
</details>

**Comment by nishakm** [comment] 2021-04-28 14:39
Huh? I get this:
```
Layer 7:
                info: Layer created by commands: /bin/sh -c npm install serve
                info: Retrieved package metadata using npm default method. 

                error: jq: error: Could not open file npm-global.json: No such file or directory
jq: error: Could not open file npm-global.json: No such file or directory
jq: error: Could not open file npm-global.json: No such file or directory
jq: error: Could not open file npm-global.json: No such file or directory
```

**Comment by JamieMagee** [comment] 2021-04-28 15:23
Since I opened this bug we migrated to `jq` for `npm` parsing. Let me re-run with a more recent version and report back.

Also, I believe that Tern should still report packages installed globally (with the `-g` flag). The example I gave of `serve` is a simple HTTP server.

**Comment by nishakm** [comment] 2021-04-28 16:10
> Also, I believe that Tern should still report packages installed globally (with the `-g` flag). The example I gave of `serve` is a simple HTTP server.

Agreed. I think we've also discovered that is bug is the result of 2 problems. 1. RUN instructions are not accurately identified and 2. npm's retrieval method is not consistent.

**Comment by rnjudge** [comment] 2021-04-28 17:14
> Huh? I get this:
> 

Not sure why we're getting different results here. I re-ran at the tip of master and still get the correct results.

**Comment by rnjudge** [comment] 2021-04-28 17:25
> Agreed. I think we've also discovered that is bug is the result of 2 problems. 1. RUN instructions are not accurately identified and 2. npm's retrieval method is not consistent.

Tern is able to parse install flags with other package managers (i.e. `apt-get install -y`) so this could be a simple logic bug?

**Comment by nishakm** [comment] 2021-04-28 19:46
> Tern is able to parse install flags with other package managers (i.e. `apt-get install -y`) so this could be a simple logic bug?

It is buildkit related, but also some docker nuances. There are 3 types of `created_by` with RUN instructions:
```
"/bin/sh -c npm install serve" <-- with WORKDIR
"/bin/sh -c RUN npm install -g serve" <-- with docker
"RUN /bin/sh -c npm install -g serve # buildkit" <-- with buildkit
```
I'll submit a PR with a fix shortly.

**Closed** 2021-04-30 23:04 UTC
