### ISSUE TITLE
"/bin/bash: cat: command not found" running example debian:buster scan

### ISSUE THREAD

**Issue by williamsmj** [tern-tools/tern#565] opened 2020-02-29 04:50 UTC
When I run `tern -l report -o output.txt -i debian:buster` as suggested in the README, I get the output below. Is this the expected output? If so, I found the repeated error messages surprising, and it might be worth clarifying in the README that this is indeed what you should see.

```
This report was generated by the Tern Project
Version: 1.0.1

Docker image: debian:buster:
	Layer: 5a87144dc3:
		info: Found 'Debian GNU/Linux 10 (buster)' in /etc/os-release.
		info: Layer created by commands: /bin/sh -c #(nop) ADD file:e05e45c33042db4ec7f71a5952d65ee8cb3786dcd76fa7a990f48a2def1344e2 in / 
		info: Retrieved by invoking listing in command_lib/base.yml
names:
	in container:
	dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'

versions:
	in container:
	pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'`
	for p in $pkgs; do dpkg -l $p | awk 'NR>5 {print $3}'; done

copyrights:
	in container:
	pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'`
	for p in $pkgs; do cat /usr/share/doc/$p/copyright; echo LICF; done




		error: /bin/bash: cat: command not found
/bin/bash: cat: command not found
/bin/bash: cat: command not found
/bin/bash: cat: command not found
/bin/bash: cat: command not found
/bin/bash: cat: command not found
/bin/bash: cat: command not found
/bin/bash: cat: command not found
/bin/bash: cat: command not found
/bin/bash: cat: command not found
[snip ~100 lines of this]
/bin/bash: cat: command not found

	Invoking commands from command_lib/base.yml:
		warning: No listing for key licenses. Consider adding this listing to command_lib/base.yml.
No listing for key srcs. Consider adding this listing to command_lib/base.yml.

	Packages found in Layer:  adduser-3.118, apt-1.8.2, base-files-10.3+deb10u3, base-passwd-3.5.46, bash-5.0-4, bsdutils-1:2.33.1-0.1, coreutils-8.30-3, dash-0.5.10.2-5, debconf-1.5.71, debian-archive-keyring-2019.1, debianutils-4.8.6.1, diffutils-1:3.7-3, dpkg-1.19.7, e2fsprogs-1.44.5-1+deb10u3, fdisk-2.33.1-0.1, findutils-4.6.0+git+20190209-2, gcc-8-base-8.3.0-6, gpgv-2.2.12-1+deb10u1, grep-3.3-1, gzip-1.9-3, hostname-3.21, init-system-helpers-1.56+nmu1, iproute2-4.20.0-2, iputils-ping-3:20180629-2, libacl1-2.2.53-4, libapt-pkg5.0-1.8.2, libattr1-1:2.4.48-4, libaudit-common-1:2.8.4-3, libaudit1-1:2.8.4-3, libblkid1-2.33.1-0.1, libbz2-1.0-1.0.6-9.2~deb10u1, libc-bin-2.28-10, libc6-2.28-10, libcap-ng0-0.7.9-2, libcap2-1:2.25-2, libcap2-bin-1:2.25-2, libcom-err2-1.44.5-1+deb10u3, libdb5.3-5.3.28+dfsg1-0.5, libdebconfclient0-0.249, libelf1-0.176-1.1, libext2fs2-1.44.5-1+deb10u3, libfdisk1-2.33.1-0.1, libffi6-3.2.1-9, libgcc1-1:8.3.0-6, libgcrypt20-1.8.4-5, libgmp10-2:6.1.2+dfsg-4, libgnutls30-3.6.7-4+deb10u2, libgpg-error0-1.35-1, libhogweed4-3.4.1-1, libidn2-0-2.0.5-1+deb10u1, liblz4-1-1.8.3-1, liblzma5-5.2.4-1, libmnl0-1.0.4-2, libmount1-2.33.1-0.1, libncursesw6-6.1+20181013-2+deb10u2, libnettle6-3.4.1-1, libp11-kit0-0.23.15-2, libpam-modules-1.3.1-5, libpam-modules-bin-1.3.1-5, libpam-runtime-1.3.1-5, libpam0g-1.3.1-5, libpcre3-2:8.39-12, libseccomp2-2.3.3-4, libselinux1-2.8-1+b1, libsemanage-common-2.8-2, libsemanage1-2.8-2, libsepol1-2.8-1, libsmartcols1-2.33.1-0.1, libss2-1.44.5-1+deb10u3, libstdc++6-8.3.0-6, libsystemd0-241-7~deb10u3, libtasn1-6-4.13-3, libtinfo6-6.1+20181013-2+deb10u2, libudev1-241-7~deb10u3, libunistring2-0.9.10-1, libuuid1-2.33.1-0.1, libxtables12-1.8.2-4, libzstd1-1.3.8+dfsg-3, login-1:4.5-1.1, mawk-1.3.3-17+b3, mount-2.33.1-0.1, ncurses-base-6.1+20181013-2+deb10u2, ncurses-bin-6.1+20181013-2+deb10u2, passwd-1:4.5-1.1, perl-base-5.28.1-6, sed-4.7-1, sysvinit-utils-2.93-8, tar-1.30+dfsg-6, tzdata-2019c-0+deb10u1, util-linux-2.33.1-0.1, zlib1g-1:1.2.11.dfsg-1
	Licenses found in Layer:  None
------------------------------------------------

###########################################
# Summary of licenses found in Container: #
###########################################
None
```
The image has cat, of course.
```
$ docker run debian:buster which cat
/bin/cat
```
I assume I'm missing something obvious!

**Comment by nishakm** [comment] 2020-03-03 20:53
@williamsmj Thanks for filing an issue. Can you paste here the digest of the image you ran tern against? You can do that by running `docker images --digests` and get the digest of the image with the name `debian` and tag `buster`.

**Comment by williamsmj** [comment] 2020-03-03 20:59
Sure, and thanks for replying! 

```
$ docker images --digests debian:buster
REPOSITORY          TAG                 DIGEST              IMAGE ID            CREATED             SIZE
docker.io/debian    buster              <none>              971452c94376        6 days ago          114 MB

$ docker pull debian:buster
Trying to pull repository docker.io/library/debian ...
buster: Pulling from docker.io/library/debian
Digest: sha256:a63d0b2ecbd723da612abf0a8bdb594ee78f18f691d7dc652ac305a490c9b71a
Status: Image is up to date for docker.io/debian:buster
```

**Comment by williamsmj** [comment] 2020-03-03 21:00
I get similar warnings about `cat not found` scanning `ubuntu:18.04` by the way.

**Comment by rnjudge** [comment] 2020-03-03 21:04
FWIW, I ran `tern -l report -o output.txt -i debian@sha256:a63d0b2ecbd723da612abf0a8bdb594ee78f18f691d7dc652ac305a490c9b71a` in my environment and do not see this warning.

**Comment by rnjudge** [comment] 2020-03-03 21:09
@williamsandrew could you share a little information about the environment you are running this command on? i.e. 
```
- Output of 'tern --version'
- Operating System (Linux Distro and version or Mac or Windows)
- Vagrant file
- Container OS
- Python version (3.6 or higher)
- Cloud environment (AWS, Azure, GCP)```

**Comment by williamsmj** [comment] 2020-03-03 21:26
Sure. Please let me know if this covers it or you need more information:

```
$ tern --version
Tern version 1.0.1
   python version = 3.6.8 (default, Aug  7 2019, 17:28:10)
[tern] mlw-cml.vpc.cloudera.com:~/tern

$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-108.git4ef4b30.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      4ef4b30/1.13.1
 Built:           Tue Jan 21 17:16:25 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-108.git4ef4b30.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      4ef4b30/1.13.1
 Built:           Tue Jan 21 17:16:25 2020
 OS/Arch:         linux/amd64
 Experimental:    false```

**Comment by nishakm** [comment] 2020-03-10 17:22
@williamsmj I ran tern on a CentOS 7 Vagrant box and I had no errors. My environment:
```
[vagrant@localhost ~]$ tern --version
Tern version 1.0.1
   python version = 3.6.8 (default, Aug  7 2019, 17:28:10) 
[vagrant@localhost ~]$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[vagrant@localhost ~]$ docker version
Client: Docker Engine - Community
 Version:           19.03.7
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        7141c199a2
 Built:             Wed Mar  4 01:24:10 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.7
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       7141c199a2
  Built:            Wed Mar  4 01:22:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
[vagrant@localhost ~]$ 
```
AFAICT, the only difference seems to be the docker version we are running (and I am not sure of the differences between Docker-CE and Docker-EE). Maybe try to upgrade your docker installation and try again?

**Comment by williamsmj** [comment] 2020-03-11 04:30
I upgraded docker to CE but get the same result with 

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.7
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        7141c199a2
 Built:             Wed Mar  4 01:24:10 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.7
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       7141c199a2
  Built:            Wed Mar  4 01:22:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

What is the output of a scan of debian:buster _supposed_ to be?

**Comment by nishakm** [comment] 2020-03-11 13:12
This is what I get when I run tern in a CentOS 7 Vagrant box:
```
[vagrant@localhost ~]$ tern -l report -i debian:buster
2020-03-10 17:14:22,687 - DEBUG - __main__ - Starting...
2020-03-10 17:14:22,687 - DEBUG - run - Setting up...
2020-03-10 17:14:22,726 - DEBUG - container - Checking if image "debian:buster" is available on disk...
2020-03-10 17:14:22,756 - DEBUG - container - Attempting to pull image "debian:buster"
2020-03-10 17:14:36,960 - DEBUG - container - Image "debian:buster" downloaded
2020-03-10 17:14:41,460 - DEBUG - rootfs - Running command: tar -tf /home/vagrant/.tern/temp.tar
2020-03-10 17:14:41,501 - DEBUG - rootfs - Running command: tar -xf /home/vagrant/.tern/temp.tar -C /home/vagrant/.tern/temp
2020-03-10 17:14:42,023 - DEBUG - rootfs - Running command: tar -tf /home/vagrant/.tern/temp/f708b10a71ac7573a7ab8a9ef412f43db00db1403a54935877a3f4d0463cb23b/layer.tar
2020-03-10 17:14:42,117 - DEBUG - rootfs - Running command: tar -xf /home/vagrant/.tern/temp/f708b10a71ac7573a7ab8a9ef412f43db00db1403a54935877a3f4d0463cb23b/layer.tar -C /home/vagrant/.tern/temp/f708b10a71ac7573a7ab8a9ef412f43db00db1403a54935877a3f4d0463cb23b/contents
2020-03-10 17:14:43,090 - DEBUG - rootfs - Running command: sudo /usr/local/lib/python3.6/site-packages/tern/tools/fs_hash.sh /home/vagrant/.tern/temp/f708b10a71ac7573a7ab8a9ef412f43db00db1403a54935877a3f4d0463cb23b/contents
2020-03-10 17:14:56,083 - DEBUG - rootfs - Running command: sudo mount -o bind /home/vagrant/.tern/temp/f708b10a71ac7573a7ab8a9ef412f43db00db1403a54935877a3f4d0463cb23b/contents /home/vagrant/.tern/temp/mergedir
2020-03-10 17:14:56,124 - DEBUG - rootfs - Running command: sudo mount -t proc /proc /home/vagrant/.tern/temp/mergedir/proc
2020-03-10 17:14:56,147 - DEBUG - rootfs - Running command: sudo mount -o bind /sys /home/vagrant/.tern/temp/mergedir/sys
2020-03-10 17:14:56,175 - DEBUG - rootfs - Running command: sudo mount -o bind /dev /home/vagrant/.tern/temp/mergedir/dev
2020-03-10 17:14:56,206 - DEBUG - rootfs - Running command: sudo cp /etc/resolv.conf /home/vagrant/.tern/temp/mergedir/etc/resolv.conf
2020-03-10 17:14:56,228 - DEBUG - rootfs - Running command: sudo unshare -pf --mount-proc=/home/vagrant/.tern/temp/mergedir/proc chroot /home/vagrant/.tern/temp/mergedir /bin/bash -c dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'
2020-03-10 17:14:56,261 - DEBUG - rootfs - Running command: sudo unshare -pf --mount-proc=/home/vagrant/.tern/temp/mergedir/proc chroot /home/vagrant/.tern/temp/mergedir /bin/bash -c pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'` && for p in $pkgs; do dpkg -l $p | awk 'NR>5 {print $3}'; done
2020-03-10 17:14:56,917 - DEBUG - rootfs - Running command: sudo unshare -pf --mount-proc=/home/vagrant/.tern/temp/mergedir/proc chroot /home/vagrant/.tern/temp/mergedir /bin/bash -c pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'` && for p in $pkgs; do cat /usr/share/doc/$p/copyright; echo LICF; done
2020-03-10 17:14:57,039 - WARNING - common - Inconsistent lengths for key: proj_urls
2020-03-10 17:14:57,044 - DEBUG - rootfs - Running command: sudo umount /home/vagrant/.tern/temp/mergedir/proc
2020-03-10 17:14:57,073 - DEBUG - rootfs - Running command: sudo umount /home/vagrant/.tern/temp/mergedir/sys
2020-03-10 17:14:57,095 - DEBUG - rootfs - Running command: sudo umount /home/vagrant/.tern/temp/mergedir/dev
2020-03-10 17:14:57,119 - DEBUG - rootfs - Running command: sudo umount -rl /home/vagrant/.tern/temp/mergedir
2020-03-10 17:14:57,177 - DEBUG - generator - Creating a detailed report of components in image...
This report was generated by the Tern Project
Version: 1.0.1

Docker image: debian:buster:
	Layer: f7aeac85f9:
		info: Found 'Debian GNU/Linux 10 (buster)' in /etc/os-release.
		info: Layer created by commands: /bin/sh -c #(nop) ADD file:e05e45c33042db4ec7f71a5952d65ee8cb3786dcd76fa7a990f48a2def1344e2 in / 
		info: Retrieved by invoking listing in command_lib/base.yml
names:
	in container:
	dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'

versions:
	in container:
	pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'`
	for p in $pkgs; do dpkg -l $p | awk 'NR>5 {print $3}'; done


copyrights:
	in container:
	pkgs=`dpkg --get-selections | cut -f1 -d':' | awk '{print $1}'`
	for p in $pkgs; do cat /usr/share/doc/$p/copyright; echo LICF; done



	Invoking commands from command_lib/base.yml:
		warning: No listing for key srcs. Consider adding this listing to command_lib/base.yml.
No listing for key licenses. Consider adding this listing to command_lib/base.yml.

	Packages found in Layer:  adduser-3.118, apt-1.8.2, base-files-10.3+deb10u3, base-passwd-3.5.46, bash-5.0-4, bsdutils-1:2.33.1-0.1, coreutils-8.30-3, dash-0.5.10.2-5, debconf-1.5.71, debian-archive-keyring-2019.1, debianutils-4.8.6.1, diffutils-1:3.7-3, dpkg-1.19.7, e2fsprogs-1.44.5-1+deb10u3, fdisk-2.33.1-0.1, findutils-4.6.0+git+20190209-2, gcc-8-base-8.3.0-6, gpgv-2.2.12-1+deb10u1, grep-3.3-1, gzip-1.9-3, hostname-3.21, init-system-helpers-1.56+nmu1, iproute2-4.20.0-2, iputils-ping-3:20180629-2, libacl1-2.2.53-4, libapt-pkg5.0-1.8.2, libattr1-1:2.4.48-4, libaudit-common-1:2.8.4-3, libaudit1-1:2.8.4-3, libblkid1-2.33.1-0.1, libbz2-1.0-1.0.6-9.2~deb10u1, libc-bin-2.28-10, libc6-2.28-10, libcap-ng0-0.7.9-2, libcap2-1:2.25-2, libcap2-bin-1:2.25-2, libcom-err2-1.44.5-1+deb10u3, libdb5.3-5.3.28+dfsg1-0.5, libdebconfclient0-0.249, libelf1-0.176-1.1, libext2fs2-1.44.5-1+deb10u3, libfdisk1-2.33.1-0.1, libffi6-3.2.1-9, libgcc1-1:8.3.0-6, libgcrypt20-1.8.4-5, libgmp10-2:6.1.2+dfsg-4, libgnutls30-3.6.7-4+deb10u2, libgpg-error0-1.35-1, libhogweed4-3.4.1-1, libidn2-0-2.0.5-1+deb10u1, liblz4-1-1.8.3-1, liblzma5-5.2.4-1, libmnl0-1.0.4-2, libmount1-2.33.1-0.1, libncursesw6-6.1+20181013-2+deb10u2, libnettle6-3.4.1-1, libp11-kit0-0.23.15-2, libpam-modules-1.3.1-5, libpam-modules-bin-1.3.1-5, libpam-runtime-1.3.1-5, libpam0g-1.3.1-5, libpcre3-2:8.39-12, libseccomp2-2.3.3-4, libselinux1-2.8-1+b1, libsemanage-common-2.8-2, libsemanage1-2.8-2, libsepol1-2.8-1, libsmartcols1-2.33.1-0.1, libss2-1.44.5-1+deb10u3, libstdc++6-8.3.0-6, libsystemd0-241-7~deb10u3, libtasn1-6-4.13-3, libtinfo6-6.1+20181013-2+deb10u2, libudev1-241-7~deb10u3, libunistring2-0.9.10-1, libuuid1-2.33.1-0.1, libxtables12-1.8.2-4, libzstd1-1.3.8+dfsg-3, login-1:4.5-1.1, mawk-1.3.3-17+b3, mount-2.33.1-0.1, ncurses-base-6.1+20181013-2+deb10u2, ncurses-bin-6.1+20181013-2+deb10u2, passwd-1:4.5-1.1, perl-base-5.28.1-6, sed-4.7-1, sysvinit-utils-2.93-8, tar-1.30+dfsg-6, tzdata-2019c-0+deb10u1, util-linux-2.33.1-0.1, zlib1g-1:1.2.11.dfsg-1
	Licenses found in Layer:  None
------------------------------------------------

###########################################
# Summary of licenses found in Container: #
###########################################
None

2020-03-10 17:14:57,178 - DEBUG - rootfs - Running command: sudo rm -rf /home/vagrant/.tern/temp/f708b10a71ac7573a7ab8a9ef412f43db00db1403a54935877a3f4d0463cb23b/contents
2020-03-10 17:14:57,350 - DEBUG - run - Teardown...
2020-03-10 17:14:58,825 - DEBUG - rootfs - Running command: sudo rm -rf /home/vagrant/.tern/temp/mergedir
2020-03-10 17:14:58,845 - DEBUG - rootfs - Running command: sudo rm -rf /home/vagrant/.tern/temp/workdir
2020-03-10 17:14:58,878 - DEBUG - __main__ - Report completed.
2020-03-10 17:14:58,879 - DEBUG - __main__ - Finished
```
We did wonder why `cat` is the only one that is not found whereas the other binaries, `cut` and `awk` seem to work fine.

**Comment by rnjudge** [comment] 2020-04-07 17:09
We had another contributor able to reproduce this issue in a CentOS environment.

**Comment by rnjudge** [comment] 2020-04-07 17:58
> We had another contributor able to reproduce this issue in a CentOS environment.

Fixing his `$PATH` by running, `export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"` seemed to fix the issue for him.

**Comment by rnjudge** [comment] 2020-04-20 19:08
As a more permanent solution, we likely need to refer to the binaries in the filesystem (i.e. use `/bin/cat` instead of `cat` to collect package information). This also means that we need to find the location of the binaries for all the listings in `base.yml`

**Comment by nishakm** [comment] 2020-04-24 17:44
@mukultaneja has a fix for this and he said he would submit a PR

**Closed** 2020-04-27 15:56 UTC
Labels: assigned
