### ISSUE TITLE
first layer no shell?

### ISSUE THREAD

**Issue by 00032118** [tern-tools/tern#776] opened 2020-07-21 09:00 UTC
Hello, when I scanned a mirror, I found that the first layer could not find a suitable shell. Is there a better way to solve this situation?
docker history as fallows:
{"architecture":"amd64","config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":["bash"],"Image":"","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{}},"container":"8c0d79930593c9444336cde5fbf995103a488d0102de14106c41773d96c9a050","container_config":{"Hostname":"8c0d79930593","Domainname":"","User":"","AttachStdin":true,"AttachStdout":true,"AttachStderr":true,"Tty":true,"OpenStdin":true,"StdinOnce":true,"Env":null,"Cmd":["bash"],"Image":"090950687196","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{}},"created":"2018-06-26T01:38:07.351157554Z","docker_version":"1.12.3","history":[{"created":"2018-06-13T03:01:28.887607447Z","comment":"Imported from -"},{"created":"2018-06-14T06:13:26.453416226Z","created_by":"sh"},{"created":"2018-06-22T06:05:14.591504952Z","created_by":"sh"},{"created":"2018-06-25T01:28:42.687842262Z","created_by":"sh"},{"created":"2018-06-26T01:19:48.90834868Z","created_by":"bash"},{"created":"2018-06-26T01:38:07.351157554Z","created_by":"bash"}],"os":"linux","rootfs":{"type":"layers","diff_ids":["sha256:7bf94991024e6ad6d2784f29b52d93b6eedd2d18ea0093fd72d5f32b20765e27","sha256:d78bda04ed8907ff94655be91125124cf905a70670c7361fafccc6a80005a76c","sha256:43b7e58cb95daafc9aff46e494c957ab53187d13b0ba1b7f878b1d6e42a81089","sha256:5a6200499ee76f95999ca2d3312f7a3af2661145ab775e7f0a47b75ef25519a0","sha256:110c6449866b602416b4c267f721a6f6120e8f846bc8cac9343587f2a2b64013","sha256:913e8e408d284b4040a6c0687ab80cca1052aba30c821f0650bf7250b8a80992"]}}

**Comment by rnjudge** [comment] 2020-07-21 15:10
Hi @00032118 - when you open an issue, please provide some information about the image and command you used to encounter the issue you are opening. We provide questions in our issue template for this purpose that are helpful for us when it comes to debugging. In this case, we don't know which "mirror" you are scanning and therefore, we cannot begin to reproduce or look in to the issue. Once we get the appropriate information from you we will try to take a look. Thanks!

**Comment by 00032118** [comment] 2020-07-22 07:37
I don’t seem to be able to directly submit the tar format image file here. I will send the email to you. Thank you for your prompt reply.

**Comment by 00032118** [comment] 2020-07-22 07:42
Sorry, due to information security reasons, I have no way to directly send you the scanned image in question. I can only provide historical information of the image making process. From the historical information, the shell was not found when identifying the first layer. It's not clear why this happened, please help.

**Comment by rnjudge** [comment] 2020-07-23 16:56
Is it possible your container's first layer filesystem doesn't have a shell present? If the container is built on top of a distroless or scratch base image, this will likely be the case. Or it could be the shell is not located in an expected location listed in `common.yml` or . Or, if you are running tern as a container and your container is Alpine based, a shell is not currently identified due to a known issue - this is documented [here](https://github.com/tern-tools/tern/issues/769) and a fix is coming shortly. Unfortunately, without the image tarball we can't provide much more than guesses as to why Tern is not finding a shell.

**Comment by 00032118** [comment] 2020-08-03 06:11
Thank you very much. The reason for your analysis is very accurate. It is true that the sh of alpine points to the absolute path of busybox. For the time being, I have not thought of a better way to solve this problem, I don’t know how you plan to improve it? Temporarily use the ln -s method to introduce a bash from the system, which can be scanned normally.

**Comment by rnjudge** [comment] 2020-08-03 19:27
If you look in the [issue](https://github.com/tern-tools/tern/issues/769) where this is documented, there are a few ways to work around this. The easiest would be install busybox in the Dockerfile/container that Tern is running.

**Comment by nishakm** [comment] 2020-09-11 17:27
I think this should be fixed with the Alpine symlink commit shipped with release 2.2.0. If it's not, please reopen this issue.

**Closed by nishakm** 2020-09-11 17:27 UTC
