### ISSUE TITLE
[SPDX][JSON] SBOM value format is incorrect for licenseDeclared

### ISSUE THREAD

**Issue by surendrapathak** [tern-tools/tern#1224] opened 2023-03-17 08:36 UTC
## Summary

SPDX value format is missing or incorrect for `licenseDeclared` on line number `1274` in the linked SBOM.

`"licenseDeclared": "LGPL-2.0+, GPL-2.0+, LGPL-2.1+",`
## Background

1. Download tern version 2.11.0
1. Generate sbom with `docker run ternd report -f spdxjson -i ubuntu:latest > output.json` for ubuntu tag latest
1. Observe the following error:

SPDX value format is missing or incorrect for `licenseDeclared`

## Expected behavior

`licenseDeclared` should be a valid SPDX string.
[Rule](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/): The exact syntax of license expressions is described below in [ABNF](http://tools.ietf.org/html/rfc5234).

Error: licenseDeclared contains ','

## Screenshots

If applicable, add screenshots to help explain the problem.

## Repository

Which repository causes this error?

- ubuntu:latest

## Additional Context

Optional - add any other context about the problem here.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team

## References
[output_fixed.json.txt](https://github.com/tern-tools/tern/files/10999391/output_fixed.json.txt)

Limited to SPDX.
Finder: [sbomqs](https://github.com/interlynk-io/sbomqs)
SBOM: [sbomlc-ubuntu-latest](attached)

**Comment by rnjudge** [comment] 2023-03-20 17:27
This is a duplicate of https://github.com/tern-tools/tern/issues/1223.

**Closed by rnjudge** 2023-03-20 17:27 UTC
Labels: duplicate, spdx
