### ISSUE TITLE
ValueError: Format string contains positional fields

### ISSUE THREAD

**Issue by chming1016** [tern-tools/tern#913] opened 2021-03-16 10:06 UTC
**Describe the bug**
While scanning images, tern raised ValueError and exit, which results in the report is not established at all.

**To Reproduce**
tern -c report -i {name}:{tag} -f json -o output.json

**Error in terminal**
```
2021-03-16 09:36:20,879 - DEBUG - core - Collecting metadata for image layer...
Traceback (most recent call last):
  File "/root/.virtualenvs/test/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/root/.virtualenvs/test/lib/python3.6/site-packages/tern/__main__.py", line 192, in main
    do_main(args)
  File "/root/.virtualenvs/test/lib/python3.6/site-packages/tern/__main__.py", line 95, in do_main
    crun.execute_image(args)
  File "/root/.virtualenvs/test/lib/python3.6/site-packages/tern/analyze/default/container/run.py", line 85, in execute_image
    cimage.analyze(full_image, args.redo, args.driver, args.extend)
  File "/root/.virtualenvs/test/lib/python3.6/site-packages/tern/analyze/default/container/image.py", line 74, in analyze
    default_analyze(image_obj, redo, driver)
  File "/root/.virtualenvs/test/lib/python3.6/site-packages/tern/analyze/default/container/image.py", line 64, in default_analyze
    image_obj, shell, master_list, redo, driver)
  File "/root/.virtualenvs/test/lib/python3.6/site-packages/tern/analyze/default/container/multi_layer.py", line 99, in analyze_subsequent_layers
    fresh_analysis(image_obj, curr_layer, shell, driver, envs)
  File "/root/.virtualenvs/test/lib/python3.6/site-packages/tern/analyze/default/container/multi_layer.py", line 63, in fresh_analysis
    image_obj.layers[curr_layer], shell, pkg_listing, envs)
  File "/root/.virtualenvs/test/lib/python3.6/site-packages/tern/analyze/default/core.py", line 52, in execute_base
    shell, listing, layer_obj.get_layer_workdir(), envs)
  File "/root/.virtualenvs/test/lib/python3.6/site-packages/tern/analyze/default/collect.py", line 102, in collect_list_metadata
    items, msg = get_pkg_attrs(listing[item], shell, work_dir, envs)
  File "/root/.virtualenvs/test/lib/python3.6/site-packages/tern/analyze/default/collect.py", line 78, in get_pkg_attrs
    snippet_list, shell, package=package_name)
  File "/root/.virtualenvs/test/lib/python3.6/site-packages/tern/analyze/default/collect.py", line 47, in invoke_in_rootfs
    full_cmd = command_lib.collate_snippets(snippet_list, package)
  File "/root/.virtualenvs/test/lib/python3.6/site-packages/tern/analyze/default/command_lib/command_lib.py", line 165, in collate_snippets
    FormatAwk(package=package)) + ' && '
ValueError: Format string contains positional fields
```

**Environment you are running Tern on**
- Output of 'tern --version'
Tern at commit 072537f4aa60b7f2962653c5960139496446f495
   python version = 3.6.8 (default, Oct  7 2019, 12:59:55)
- Operating System (Linux Distro and version or Mac or Windows)
Ubuntu 18.04.3 LTS
- Container OS
Ubuntu 20.04.2 LTS
- Python version (3.6 or higher)
Python 3.6.8

**Comment by rnjudge** [comment] 2021-03-17 03:45
Hi @chming1016, thanks for opening this issue.

Could you please include the image and tag you are seeing this issue with? I can't reproduce with a few that I've tried (`photon:3.0`, `alpine:latest`, `debian:buster`, and`golang:latest`) at the tip of main.

I'm also having a hard time finding this commit: 072537f4aa60b7f2962653c5960139496446f495. Could you run: `git log --oneline` in your development environment and show me the first few lines where this commit might be coming from?

**Comment by chming1016** [comment] 2021-03-17 10:54
Hi @rnjudge, 

Sorry for giving the wrong tern commit. Following is the right one I am current using.
- d6ca178 Set SPDX PackageDownloadLocation to valid value

Unfortunately, I can not give the specific image name and tag due to the image is hosted in a private registry and I am not authorized to give this in public.

However, I am able to reproduce within the following Dockerfile.

```
FROM ubuntu:20.04
RUN apt-get update && \
    apt-get install -y python3 python3-pip
RUN pip3 install --upgrade pip==9.0.3
COPY patch patch
# Patch some stuffs. Patch name MUST be something like 01-pip-desc
RUN for i in `ls patch`; \
    do module_name=$(echo $i | awk -F '-' '{print $2}'); \
    patch -d $(pip3 show $module_name | grep Location | awk '{print $2}') -p1 < patch/$i; \
    done
RUN rm -r patch
ENV TEST_ENDPOINT=https://test.myapi.com/v1/AUTH_{}
CMD ["/bin/sh"]
```
**To Reproduce**

- docker build -t testimage/testtag:1.0
- tern -c report -i testimage/testtag:1.0 -f json -o output.json

**Comment by rnjudge** [comment] 2021-03-17 16:24
Ok, I can reproduce at the tip of main. I'll take a look, thanks!

**Comment by rnjudge** [comment] 2021-03-18 06:07
The issue Tern is having is with the `TEST_ENDPOINT=https://test.myapi.com/v1/AUTH_{}` line of the Dockerfile. In the `collate_snippets()` function in `command_lib.py`, Tern runs `format_map()` on each element of the snippet list in order to concatenate the snippet commands into one command. `format_map()` is a built in function in Python which take a dictionary as input and returns the key's values of the input dictionary.

The snippet for the `ENV` command in the Dockerfile is `export <ENV command>`. The incompatibility here is with `{}` in the Dockerfile line, which Python is interpreting as a string to be formatted instead of just part of the larger string as it was intended. I can reproduce this in the repl:

```
>>> 'export TEST_ENDPOINT=https://test.myapi.com/v1/AUTH_{}'.format_map({})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Format string contains positional fields
```

If you remove the `{}` from the Dockerfile `ENV` line, there's no issue running Tern. I'll work on a fix for this and open a PR.

**Closed** 2021-03-19 23:55 UTC
Labels: bug
