### ISSUE TITLE
Installation instructions with vagrant don't work on my system

### ISSUE THREAD

**Issue by arun-kumar2** [tern-tools/tern#1184] opened 2022-08-03 08:38 UTC
**Describe the bug**
Unable to start tern with the instructions given for vagrant,
I followed the instructions in the "Getting Started with Vagrant" section in the Readme: https://github.com/tern-tools/tern.
When i do vagrant up, i get a message saying that:
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If i start the VM in Virtualbox, i see this error: dependency failed for hyper-v kvp protocol daemon

**To Reproduce**
1. Follow the instructions in the "Getting Started with Vagrant" section in the Readme: https://github.com/tern-tools/tern.
2. run vagrant up
3. i get a message saying that:
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If i start the VM in Virtualbox, i see this error: dependency failed for hyper-v kvp protocol daemon
![image](https://user-images.githubusercontent.com/91262131/182563518-e25d794e-7852-48c0-9969-095dbe2262a0.png)

**Expected behavior**
VM should start without any errors to enable me to use tern

**Environment you are running Tern on**
Enter all that apply
- Output of 'tern --version'  - NA
- Operating System (Linux Distro and version or Mac or Windows)
Git bash on Windows 10
- Vagrant file
Same as the one mentioned in the instructions - from your repo
- Container OS
Ubuntu
- Python version (3.6 or higher)
3.6.7
- Cloud environment (AWS, Azure, GCP)
NA
**Please attach files if they exist**
- tern.log
- report.*
NA

**Comment by rnjudge** [comment] 2022-12-08 18:17
Hi @arun-kumar2, I'm not sure that this is a Tern error. Sounds like there might be a dependency missing on your system perhaps? But I will give it a try and see if I can reproduce.

**Comment by rnjudge** [comment] 2022-12-09 19:15
I overlooked the fact that you are working on a Windows computer so I won't be able to attempt to reproduce since I have a Mac. I was able to find a similar bug that you're seeing open in the Ubuntu bugset: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1820063

I'm sorry I can't be more helpful. But closing this bug since it's not related to Tern, rather, it's an issue with vagrant on windows.

**Closed by rnjudge** 2022-12-09 19:15 UTC
