### ISSUE TITLE
Running tern with podman returns cert error

### ISSUE THREAD

**Issue by muzammil786** [tern-tools/tern#1087] opened 2021-11-23 18:26 UTC
How can we run turnd analysis using podman. I tried by creating the podman socket and using the command below:

`sudo podman run --privileged --device /dev/fuse -v /run/podman/podman.sock:/var/run/docker.sock:z --rm ternd report -i python:3.9-slim-buster > output.txt
`
But it got errors like:

```
2021-11-23 18:19:10,954 - DEBUG - rootfs - Running command: unshare -pf --mount-proc=/root/.tern/temp/mergedir/proc chroot /root/.tern/temp/mergedir  -c export PYTHON_GET_PIP_SHA256="c518250e91a70d7b20cceb15272209a4ded2a0c263ae5776f129e0d9b5674309" && export PYTHON_GET_PIP_URL="https://github.com/pypa/get-pip/raw/3cb8888cc2869620f57d5d2da64da38f516078c7/public/get-pip.py" && export PYTHON_SETUPTOOLS_VERSION="57.5.0" && export PYTHON_PIP_VERSION="21.2.4" && export PYTHON_VERSION="3.9.9" && export GPG_KEY="E3FF2839C048B25C084DEBE9B26995E310250568" && export LANG="C.UTF-8" && export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" && pkgs=`dpkg-query -W -f '${Package}
'` && for p in $pkgs; do /bin/cat /usr/share/doc/$p/copyright; echo LICF; done
2021-11-23 18:19:10,973 - ERROR - rootfs - Command failed. chroot: failed to run command ‘’: No such file or directory
```

**Comment by nishakm** [comment] 2021-12-21 15:32
@muzammil786 We made a release recently that removed docker as a dependency for analyzing container images. Try:
`sudo podman run --rm ternd report -i python:3.9-slim-buster > output.txt` after rebuilding the new [Dockerfile](https://github.com/tern-tools/tern/blob/main/docker/Dockerfile)

**Comment by muzammil786** [comment] 2022-01-06 11:55
@nishakm 
I have got certificate validation error:

2022-01-06 11:27:58,117 - ERROR - skopeo - Error when downloading image: "b'time="2022-01-06T11:27:58Z" level=fatal msg="Error initializing source docker://<redact>: error pinging docker registry <private registry>: Get \\"https://<priate registry>/v2/\\": x509: certificate signed by unknown authority"\n'"

How to send src-tls-verify=false option to skopeo or mount the cert dir? Is there any env variable I can pass to ignore cert validation?

**Comment by nishakm** [comment] 2022-01-06 13:54
@muzammil786 not at this time. We can probably modify the Dockerfile to create a volume mount. Or podman perhaps has some way of enabling this. I will take a look.

**Comment by muzammil786** [comment] 2022-01-06 14:57
@nishakm Thanks. I have sorted this out by adding my registry into the base image. 

`COPY registries.conf /etc/containers/registries.conf`

This line in the docker/Dockerfile helped me sail for now :-)

**Comment by nishakm** [comment] 2022-02-03 15:59
I am not able to reproduce this error when running `sudo podman run --privileged --rm tern report -i python:3.9-slim-buster`. At this time, running podman as root and using `--privileged` is the only way to get around the permission issues when creating device nodes (see #1115 ). I will close this issue.

**Closed** 2022-02-03 16:00 UTC
Labels: feature
