### ISSUE TITLE
Rearrange functions in lock.py and parse.py

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#826] opened 2020-11-10 23:47 UTC
**Description**
The functions in lock.py and parse.py are not necessarily related to Dockerfile parsing and/or Dockerfile lock.

**To Do**
1. Identify the functions that could be moved or refactored.
2. After moving them to the appropriate place, fix imports.
3. Functional tests.

**Super Issues**
#801

**Comment by nishakm** [comment] 2021-03-08 19:27
@m1-key This one may need some refactor.

**Comment by m1-key** [comment] 2021-03-08 20:33
> @m1-key This one may need some refactor.

Okay @nishakm, I will make a report of the steps that are required to remove or required refactoring according to my knowledge, and will share the same with you.

**Comment by m1-key** [comment] 2021-03-16 22:29
@nishakm @rnjudge Here is what I found after having a deep look at `parse.py` and `lock.py`

For `parse.py`:

- There is a function named `get_installed_packages` which is not used anywhere in the entire repository.
- Other than this all the functions are either called directly in `dockerfile/run.py` or in `lock.py` and from there those functions of `lock.py` are called in `dockerfile/run.py`.

For `lock.py`:

- There are two functions named `get_dockerfile_image_tag` and `get_commands_from_history` which are not used anywhere in the program.
- There is a function named `get_env_vars` which I think should be in `parse.py`. I have attached the function below.
   <details>
  <summary>get_env_vars</summary>
  
  ```python
      def get_env_vars(image_obj):
          '''Given a docker image object, return the list of environment variables,
          if any, based on their values in the config.'''
          config = image_obj.get_image_config(image_obj.get_image_manifest())
          # replace '\t' with '\\t'  in the ENV
          for idx, env_str in enumerate(config['config']['Env']):
              config['config']['Env'][idx] = env_str.replace('\t', '\\t')
          return config['config']['Env']
  ```
</details>

Apart from the above-mentioned functions, all other functions have their role in `dockerfile/run.py`

**Comment by dk-github-acc** [comment] 2021-09-05 17:43
Hi @nishakm @m1-key. The issue has been labelled as technical debt and for near-future. If the issue is ready to be solved now, can I take it up? Can you please assign this issue to me?

**Closed** 2021-10-02 20:50 UTC
Labels: refactor, intermediate, technical-debt
